spring:

  # ===============================
  # = ThymeLeaf
  # ===============================
  thymeleaf:
    cache: false

  # ===============================
  # = MariaDB
  # ===============================
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/znzn
#    username: sa

  datasource:
    url: jdbc:mariadb://znzn.synology.me:3306/znzn01
    username: znzn02
    password: znzn02

  # ===============================
  # = AWS Mysql
  # ===============================
#  datasource:
#    url: jdbc:mysql://docker-mysql-test.c0smsauwtlw2.ap-northeast-2.rds.amazonaws.com:3306?serverTimezone=UTC&characterEncoding=UTF-8
#    username: user
#    password: znzn9292!
#    driver-class-name: com.mysql.jdbc.Driver

  # ===============================
  # = JPA / Hibernate
  # ===============================
  jpa:
    hibernate:
      ddl-auto: none

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
